### ISSUE TITLE
Selenium in headless linux system

### ISSUE THREAD

**Issue by wikibootup** [wikibootup/hashtags#2]
From good references 
- https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
- http://jellyms.kr/804

I used it in Django environment. like below
```yml
language: python

python:
  - "3.5"

dist: trusty
sudo: required
addons:
  packages:
    - unzip
    - google-chrome-stable

before_install:
    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/

    # For selenium in headless linux system
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
...
```
